export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_BY_ID = "GET_ALL_USER_BY_ID";
export const GET_PAGINATION_SEARCH = "GET_PAGINATION_SEARCH";
export const GET_SEARCH_USER_BY_USERS = "GET_SEARCH_USER_BY_USERS";
