export const GET_ALL_RENTAL_ROOM = "GET_ALL_RENTAL_ROOM";
export const GET_ALL_RENTAL_ROOM_BY_ID = "GET_ALL_RENTAL_ROOM_BY_ID";
export const GET_PAGINATION_SEARCH = "GET_PAGINATION_SEARCH";
export const GET_SEARCH_RENTAL_ROOM_BY_LOCATION =
  "GET_SEARCH_RENTAL_ROOM_BY_LOCATION";
